# Use official python image
FROM python:3.12

# Set working directory inside container
WORKDIR /app

# Copy local python script into container current working directory
COPY app.py .

# Command to run script when the container starts
CMD ["python", "app.py"]